AdminTour/Controllers/InverseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminTour.Processors;
using KIT.Helpers;
using KIT.Models.BaseModels;
using KIT.ModelsVm;

namespace AdminTour.Controllers
{
    public class InverseController : AdminController
    {
        //private readonly PaymentProcessor _paymentProcessor;
        private readonly InverseListProcessor _inverseListProcessor;
        private readonly InverseProcessor _inverseProcessor;

        public InverseController()
        {
           // _paymentProcessor = new PaymentProcessor(CommonRepository);
            _inverseListProcessor = new InverseListProcessor(CommonRepository);
            _inverseProcessor = new InverseProcessor(CommonRepository);
        }
        // GET: Inverse
        public ActionResult Index()
        {
            return View(_inverseListProcessor.ToFilteredResult);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Index(ListViewModel<InverseContactVm, InverseFilter> viewModel)
        {
            
            _inverseListProcessor.Initialize(viewModel);

            return View(_inverseListProcessor.ToFilteredResult);
        }

        [HttpGet]
        public ActionResult ChangeStatus(long id)
        {
            return Json(new { html = this.PartialViewToString("_inverse", _inverseProcessor.InverseStatus(id)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult ChangeStatus(InverseStatusVm inverseStatusVm)
        {
            _inverseProcessor.ChangeStatus(inverseStatusVm);
            return Json(new { status = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

AdminTour/Controllers/InverseTourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminTour.Processors;
using KIT.Helpers;
using KIT.Models.BaseModels;
using KIT.ModelsVm;

namespace AdminTour.Controllers
{
    public class InverseTourController : AdminController
    {
        private readonly InverseTourListProcessor _inverseTourListProcessor;
        private readonly InverseTourProcessor _inverseTourProcessor;

        public InverseTourController()
        {
            _inverseTourListProcessor = new InverseTourListProcessor(CommonRepository);
            _inverseTourProcessor = new InverseTourProcessor(CommonRepository);
        }


        // GET: InverseTour
        public ActionResult Index()
        {
            return View(_inverseTourListProcessor.ToFilteredResult);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Index(ListViewModel<InverseTourVm, InverseTourFilter> viewModel)
        {
            _inverseTourListProcessor.Initialize(viewModel);
            return View(_inverseTourListProcessor.ToFilteredResult);
        }

        [HttpGet]
        public ActionResult ChangeStatus(long id)
        {
            return Json(new { html = this.PartialViewToString("_inverse", _inverseTourProcessor.GetInverseStatus(id)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult ChangeStatus(InverseStatusVm inverseStatusVm)
        {
            _inverseTourProcessor.ChangeStatus(inverseStatusVm);
            return Json(new { status = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult IssuesInfo(long id)
        {
            return Json(new { html = this.PartialViewToString("_infoInverse", _inverseTourProcessor.GetInfoInverseTourVm(id)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ChangeInverse(long id)
        {
            return Json(new { html = this.PartialViewToString("_changeInverseTour", _inverseTourProcessor.GetInfoInverseTourVm(id)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult ChangeInverse(InverseInfoTourVm inverseInfoTourVm)
        {
            Dictionary<string, string> errors;
            if (!_inverseTourProcessor.IsValidChangeInverse(inverseInfoTourVm, out errors))
                return Json(new { status = false, errors }, JsonRequestBehavior.AllowGet);

            _inverseTourProcessor.ChangeInverseTour(inverseInfoTourVm);
            return Json(new { status = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

AdminTour/Views/InverseTour/Index.cshtml
@using KIT.Enums
@using KIT.Helpers
@using KIT.Helpers.Controls
@model KIT.Models.BaseModels.ListViewModel<KIT.ModelsVm.InverseTourVm,KIT.ModelsVm.InverseTourFilter>


@{
    ViewBag.Title = "Заявки";
    var person = AccessContext.GetAccount;
}
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <div class="col-lg-12">
                <div>
                    <h4 class="float-left">Заявки</h4>
                </div>
                <div class="clearfix m-bot-15"></div>

                @using (Html.BeginForm("Index", "InverseTour", FormMethod.Post, new { id = "filter-table" }))
                {
                    <div class="row">
                        <div class="col-lg-4">
                            @Html.GroupDateTimeRangeFor(w => w.Filters.DateStart, x => x.Filters.DateEnd, "Период")
                        </div>
                        <div class="col-lg-3">
                            @Html.LabelForModel("ФИО")
                            @Html.TextBoxFor(w => w.Filters.FullName, new { @class = "form-control", placeholder = "--ВСЕ--" })
                        </div>
                        <div class="col-lg-3">
                            @Html.LabelForModel("Тур")
                            @Html.DropDownListFor(w => w.Filters.Tour, Model.Filters.Tours, "--ВСЕ--", new { @class = "form-control" })
                        </div>
                        <div class="col-lg-2">
                            @Html.LabelForModel("Статус заявки")
                            @Html.DropDownListFor(w => w.Filters.BidStatus, Model.Filters.Statuses, "--ВСЕ--", new { @class = "form-control" })
                        </div>
                        <div class="clearfix"></div>
                        
                        
                        <div class="clearfix"></div>
                        <div class="col-lg-12 text-center m-top-15">
                            <button type="submit" class="btn btn-primary btn-sm text-uppercase"><i class="fa fa-search"></i> Поиск</button>
                        </div>
                    </div>
                    <hr />
                    @Html.PageSize(Model.PageInfo)
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>@Html.FieldSortByTable(Model.PageInfo, "Id", "Номер")</th>
                            <th>@Html.FieldSortByTable(Model.PageInfo, "CreateDate", "Время")</th>
                            <th>@Html.FieldSortByTable(Model.PageInfo, "FullName", "ФИО")</th>
                            <th>@Html.FieldSortByTable(Model.PageInfo, "TourName", "Тур")</th>
                            <th>@Html.FieldSortByTable(Model.PageInfo, "BidStatus", "Статус заявки")</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>@item.id</td>
                                <td>@item.CreateDate</td>
                                <td>@item.FullName</td>
                                <td>@item.TourName</td>

                                @if (item.BidStatus == ContactStatus.Success)
                                {
                                    <td><span class="label label-success">@ContactStatus.Success.Description()</span></td>
                                }
                                else if (item.BidStatus == ContactStatus.Rejected)
                                {
                                    <td><span class="label label-danger">@ContactStatus.Rejected.Description()</span></td>
                                }
                                else
                                {
                                    <td><span class="label label-default">@ContactStatus.New.Description()</span></td>
                                }

                                @*<td><button type="button" class="btn btn-primary btn-xs" let="info-payment" rid="@item.Id">@Localization.Resource.Показать</button></td>*@
                                <td>
                                    <button type="button" class="btn btn-info btn-xs" let="info-inverse" rid="@item.id">Подробнее</button>
                                </td> 
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" let="change-status" rid="@item.id">Сменить статус</button>
                                </td>  
                                <td>
                                    <button type="button" class="btn btn-default btn-xs" let="change-inverse" rid="@item.id">Корректировать</button>
                                </td>  
                            </tr>
                        }
                        </tbody>
                    </table>
                    @Html.Paginator(Model.PageInfo)
                    @Html.AntiForgeryToken()
                }
            </div>
        </div>
    </div>
</div>

<script src="@Url.Content("~/Scripts/view.processor/inverseTour.view.processor.js")"></script>
<script>
    $(function() {
        var config = {
            url: {
               info: '@Url.Action("IssuesInfo")',
               change: '@Url.Action("ChangeInverse")',
                changeStatus: '@Url.Action("ChangeStatus")'

            },
            resource: {
                changeTitle: 'Корректировка заявки',
                changeStatusTitle: 'Смена статуса заявки',
                infoTitle: 'Информация по заявке',
                save: 'Сохранить',
                cancel: 'Отмена',
                close: 'Закрыть',
                operationComplete: 'Операция завершена. ',
                changeIsComplete: 'Запись успешно изменена. Для отображения результата обновите страницу.',
                changeStatusIsComplete: 'Статус заявки изменен. Для отображения результата обновите страницу.'
            }
        };
        var processor = new InverseTourViewProcessor(config);
        processor.Start();
    })
</script>

AdminTour/Views/InverseTour/_changeInverseTour.cshtml
@using KIT.Enums
@using KIT.Helpers
@model KIT.ModelsVm.InverseInfoTourVm
@using KIT.Helpers.Controls
<form let="change-inverse-form">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(w=>w.id)
    @Html.HiddenFor(w=>w.CreateDate)
    <table class="table">
        <tbody>
        <tr>
            <th class="align-middle">Номер заявки</th>
            <td let="id">@Model.id</td>
        </tr>
        <tr>
            <th class="align-middle">Дата создания заявки</th>
            <td let="CreateDate">@Model.CreateDate</td>
        </tr>
            <tr>
                <th class="align-middle">ФИО</th>
                <td>
                    @Html.TextBoxFor(w => w.FullName, new { @class = "form-control", let = "FullName" })
                    <span valid-for="FullName" class="validate_fild"></span>
                </td>
            </tr>
            <tr>
                <th class="align-middle">Почта</th>
                <td>
                    @Html.TextBoxFor(w => w.Email, new { @class = "form-control", let = "Email" })
                    <span valid-for="Email" class="validate_fild"></span>
                </td>
            </tr>
            <tr>
                <th class="align-middle">Номер телефона</th>
                <td>
                    @Html.TextBoxFor(w => w.PhoneNumber, new { @class = "form-control", let = "PhoneNumber" })
                    <span valid-for="PhoneNumber" class="validate_fild"></span>
                </td>
            </tr>
        <tr>
            <th class="align-middle">Тур</th>
            <td>
                @Html.DropDownListFor(w => w.TourId, Model.Tours, new { @class = "form-control" })
                <span valid-for="Tour" class="validate_fild"></span>
            </td>
        </tr>
        <tr>
            <th class="align-middle">Количество людей</th>
            <td>
                @Html.TextBoxFor(w => w.PeopleCount, new { @class = "form-control", let = "PeopleCount" })
                <span valid-for="PeopleCount" class="validate_fild"></span>
            </td>
        </tr>
        <tr>
            <th class="align-middle">Страна/Город вылета</th>
            <td>
                @Html.TextBoxFor(w => w.CityFly, new { @class = "form-control", let = "CityFly" })
                <span valid-for="CityFly" class="validate_fild"></span>
            </td>
        </tr>
        <tr>
            <th class="align-middle">Дата вылета</th>
            <td>
                @Html.DateTimePickerFor(w => w.DateFly)
                <span valid-for="DateFly" class="validate_fild"></span>
            </td>
        </tr>
        <tr>
            <th class="align-middle">IP адрес</th>
            <td>@Model.IpAdress</td>
        </tr>
        <tr>
            <th class="align-middle">Статус заявки</th>
            @if (Model.BidStatus == ContactStatus.Success)
            {
                <td><span class="label label-success">@ContactStatus.Success.Description()</span></td>
            }
            else if (Model.BidStatus == ContactStatus.Rejected)
            {
                <td><span class="label label-danger">@ContactStatus.Rejected.Description()</span></td>
            }
            else
            {
                <td><span class="label label-default">@ContactStatus.New.Description()</span></td>
            }
        </tr>
        </tbody>
    </table>
</form>

AdminTour/Views/InverseTour/_infoInverse.cshtml
@using KIT.Enums
@using KIT.Helpers
@using KIT.Helpers.Controls
@using Localization
@model KIT.ModelsVm.InverseInfoTourVm

<form let="InverseInfo-form">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(w => w.id)
    <table class="table">
        <tbody>
        <tr>
            <th class="align-middle">Номер заявки</th>
            <td>@Model.id</td>
        </tr>
        <tr>
            <th class="align-middle">Дата создания заявки</th>
            <td>@Model.CreateDate</td>
        </tr>
        <tr>
            <th class="align-middle">ФИО</th>
            <td>@Model.FullName</td>
        </tr>
        <tr>
            <th class="align-middle">Почта</th>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <th class="align-middle">Номер телефона</th>
            <td>@Model.PhoneNumber</td>
        </tr>
        <tr>
            <th class="align-middle">Тур</th>
            <td>@Model.NameTour</td>
        </tr>
        <tr>
            <th class="align-middle">Количество людей</th>
            <td>@Model.PeopleCount</td>
        </tr>
        <tr>
            <th class="align-middle">Страна/Город вылета</th>
            <td>@Model.CityFly</td>
        </tr>
        <tr>
            <th class="align-middle">Дата вылета</th>
            <td>@Model.DateFly</td>
        </tr>
        <tr>
            <th class="align-middle">IP адрес</th>
            <td>@Model.IpAdress</td>
        </tr>
        <tr>
            <th class="align-middle">Статус заявки</th>
            @if (Model.BidStatus == ContactStatus.Success)
            {
                <td><span class="label label-success">@ContactStatus.Success.Description()</span></td>
            }
            else if (Model.BidStatus == ContactStatus.Rejected)
            {
                <td><span class="label label-danger">@ContactStatus.Rejected.Description()</span></td>
            }
            else
            {
                <td><span class="label label-default">@ContactStatus.New.Description()</span></td>
            }
        </tr>
        </tbody>
    </table>
</form>

AdminTour/Views/InverseTour/_inverse.cshtml
@using KIT.Helpers
@using Localization
@model KIT.ModelsVm.InverseStatusVm

<form let="change-status-form">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(w => w.id)
    <table class="table">
        <tbody>
            <tr>
                <th class="align-middle">ID заявки</th>
                <td>@Model.id</td>
            </tr>
            <tr>
                <th class="align-middle">Статус заявки</th>
                <td>
                    @Html.DropDownListFor(w => w.InverseStatus, Model.Statuses, new { @class = "form-control" })
                    <span valid-for="PaymentStatus" class="validate_fild"></span>
                </td>
            </tr>

        </tbody>
    </table>
</form>