Touring/Controllers/BanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Touring.Controllers
{
    public class BanController : Controller
    {
        // GET: Ban
        public ActionResult Index()
        {
            return View();
        }
    }
}

Touring/Controllers/ClientController.cs
using System;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using KIT.Enums;
using KIT.Enums.Extensions;
using KIT.Models;
using KIT.Repositories;
using Localization;
using Touring.Filters;

namespace Touring.Controllers
{
    [Culture]
    public class ClientController : Controller
    {
        protected readonly ICommonRepository CommonRepository;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var ip = HttpContext.Request.UserHostAddress;
            var ipadres = CommonRepository.SingleOrDefault<Security>(w => w.Ip == ip);
            if (ipadres != null)
            {
                filterContext.Result = new RedirectResult("/Ban");
                return;
            }
        }

        public ClientController()
        {
            CommonRepository = new CommonRepository();
        }

        protected override void Dispose(bool disposing)
        {
            CommonRepository.Dispose();
            base.Dispose(disposing);
        }

        [HttpGet, AllowAnonymous]
        public ActionResult ChangeCulture(Language langEnum)
        {
            var lang = langEnum.ToLowerString();

            var cultures = Enum.GetValues(typeof(Language)).Cast<Language>().Select(w => w.ToLowerString()).ToList();
            if (!cultures.Contains(lang))
                lang = Language.Ru.ToLowerString();

            var cookie = Request.Cookies["lang"];
            if (cookie != null)
                cookie.Value = lang;
            else
            {
                cookie = new HttpCookie("lang")
                {
                    HttpOnly = false,
                    Value = lang,
                    Expires = DateTime.Now.AddYears(1)
                };
            }

            Response.Cookies.Add(cookie);
            if (Request.UrlReferrer == null)
                return RedirectToAction("Index", "Home");

            return Redirect(Request.UrlReferrer.PathAndQuery);
        }

        protected Language GetCurrentCulture
        {
            get
            {
                var cookie = Request.Cookies["lang"];
                return cookie?.Value.ToEnum<Language>() ?? Language.Ru;
            }
        }

        public ActionResult GetResourceByKey(string key)
        {
            var resourceValue = Resource.ResourceManager.GetString(key);
            return Json(new { value = resourceValue }, JsonRequestBehavior.AllowGet);
        }

    }
}

Touring/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KIT.Helpers;
using Touring.ModelsVm;
using Touring.Processors;

namespace Touring.Controllers
{
    public class HomeController : ClientController
    {
        private readonly HomeProcessor _homeProcessor;

        public HomeController()
        {
            _homeProcessor = new HomeProcessor(CommonRepository);
        }

        public ActionResult Index()
        {
            return View(_homeProcessor.GetData());
        }


        [HttpGet]
        public ActionResult AddInverse(string email)
        {
            return Json(new { html = this.PartialViewToString("_addinversecontact", _homeProcessor.GetInverseContactVm(email)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult AddInverses(InverseContactVm inverseContactVm)
        {
            Dictionary<string, string> errors;
            if (!_homeProcessor.IsValidInverse(inverseContactVm, out errors))
                return Json(new { status = false, errors }, JsonRequestBehavior.AllowGet);
            inverseContactVm.IpAdress = Request.UserHostAddress;
            _homeProcessor.SaveInverseContact(inverseContactVm);
            return Json(new { status = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

Touring/Controllers/IssuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Touring.Processors;

namespace Touring.Controllers
{
    public class IssuesController : ClientController
    {
        private readonly IssuesProcessor _issuesProcessor;

        public IssuesController()
        {
            _issuesProcessor = new IssuesProcessor(CommonRepository);
        }

        // GET: Issues
        public ActionResult Index()
        {
            return View(_issuesProcessor.GetData());
        }
    }
}

Touring/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KIT.Helpers;
using Touring.ModelsVm;
using Touring.Processors;

namespace Touring.Controllers
{
    public class TourController : ClientController
    {

        private readonly TourProcessor _tourProcessor;

        public TourController()
        {
            _tourProcessor = new TourProcessor(CommonRepository);
        }

        // GET: Tour
        public ActionResult Index(long id)
        {
            return View(_tourProcessor.GetData(id));
        }


        [HttpGet]
        public ActionResult AddInverse(long id)
        {
            return Json(new { html = this.PartialViewToString("_addinverse", _tourProcessor.GetInverseVm(id)) }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult AddInverses(InverseVm inverseVm)
        {
            Dictionary<string, string> errors;
            if (!_tourProcessor.IsValidInverse(inverseVm, out errors))
                return Json(new { status = false, errors }, JsonRequestBehavior.AllowGet);
            inverseVm.IpAdress=Request.UserHostAddress;
            _tourProcessor.SaveInverse(inverseVm);
            return Json(new { status = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

Touring/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Touring.Processors;

namespace Touring.Controllers
{
    public class VideoController : ClientController
    {
        private readonly VideoProcessor _videoProcessor;

        public VideoController()
        {
            _videoProcessor = new VideoProcessor(CommonRepository);
        }


        // GET: Video
        public ActionResult Index()
        {
            return View(_videoProcessor.GetData());
        }
    }
}

Touring/Views/Ban/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Ban";
    Layout = null;
}

<h2 style="color: red; text-align: center; margin-top: 40px;">Your IP Adress has been banned!</h2>
<img style="margin-left: 525px" src="~/Content/assets/img/ban.png"/>

Touring/Views/Issues/Index.cshtml
@using KIT.Enums
@using Localization
@using Touring.Controls
@model Touring.ModelsVm.IssuesVmPage

@{
    ViewBag.Title = "Issues";
}

<div id="body-bg">
    @Html.Partial("_sidebar",Model.ContactVm)
    <div id="pre-header" class="container" style="height: 40px;">
    </div>
    <div id="header">
        <div class="container">
            <div class="row">
                <!-- Logo -->
                <div class="logo">
                    <a href="@Url.Action("Index","Home")" title="">
                        <img src="~/Content/assets/img/logo.png" alt="Logo"/>
                    </a>
                </div>
                <!-- End Logo -->
            </div>
        </div>
    </div>
    <!-- Top Menu -->
    <div id="hornav" class="container no-padding">
        <div class="row">
            <div class="col-md-12 no-padding">
                <div class="text-center visible-lg">
                    <ul id="hornavmenu" class="nav navbar-nav">
                        <li>
                            <a href="@Url.Action("Index","Home")" class="fa-home">@Resource.Домой</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Home")" class="fa-plane">@Resource.Туры</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Video")" class="fa-th">@Resource.Портфолио</a>
                        </li>
                        @*<li>
                        <a href="../Home/portfolio-2-column.html" class="fa-comments-o">@Resource.Часто_задаваемые_вопросы</a>
                    </li>*@
                        <li>
                            <a href="#contact" class="fa-comment go_to">@Resource.Обратная_связь</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Menu -->
    <div id="post_header" class="container" style="height: 40px;">
    </div>
    <div id="content-top-border" class="container">
    </div>
    <!-- === END HEADER === -->
    <!-- === BEGIN CONTENT === -->
    <div id="content">
        <div class="container background-white">
            <div class="row margin-vert-30">
                <div class="col-md-12">
                    <h2>@Resource.Часто_задаваемые_вопросы</h2>
                    <p>@Resource.Текст_часто_задаваемые_вопросы</p>
                    <hr class="margin-vert-40">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="tab-content">
                                <div class="tab-pane active in fade" id="faq">
                                    <div class="panel-group" id="accordion">
                                        <!-- FAQ Item -->
                                        @foreach (var faq in Model.IssuesVm)
                                        {
                                            <div class="panel panel-default panel-faq">
                                                <div class="panel-heading">
                                                    <a data-toggle="collapse" data-parent="#accordion" href="#faq-sub">
                                                        <h4 class="panel-title">
                                                            @faq.Issues
                                                            <span class="pull-right">
                                                                <i class="glyphicon glyphicon-plus"></i>
                                                            </span>
                                                        </h4>
                                                    </a>
                                                </div>
                                                <div id="faq-sub" class="panel-collapse collapse">
                                                    <div class="panel-body">
                                                        @faq.Answer
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    
                                    
                                   
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <h3 class="margin-bottom-10">@Resource.Не_нашли_ответы</h3>
                            <p>@Resource.Вы_можете</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- === END CONTENT === -->
    <!-- === BEGIN FOOTER === -->
    <div id="contact"></div>
    @Html.Partial("_footer",Model.ContactVm)
</div>

<script>
    $(document).ready(function(){
        $('.go_to').click( function(){ // ловим клик по ссылке с классом go_to
            var scroll_el = $(this).attr('href'); // возьмем содержимое атрибута href, должен быть селектором, т.е. например начинаться с # или .
            if ($(scroll_el).length != 0) { // проверим существование элемента чтобы избежать ошибки
                $('html, body').animate({ scrollTop: $(scroll_el).offset().top }, 900); // анимируем скроолинг к элементу scroll_el
            }
            return false; // выключаем стандартное действие
        });
    });
</script>

Touring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <!-- Favicon -->
    <link href="favicon.ico" rel="shortcut icon">
    @Styles.Render("~/Content/layout")
    <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=PT+Sans" type="text/css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">
    @Scripts.Render("~/bundles/layout")
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
    (function(){ var widget_id = 'CX9t8n1unt';var d=document;var w=window;function l(){
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script>
    <!-- {/literal} END JIVOSITE CODE -->
</head>
<body>
        @RenderBody()
</body>
</html>

Touring/Views/Shared/_footer.cshtml
@using Localization
@using Touring.ModelsVm
<div id="content-bottom-border" class="container">
</div>
<div id="base">
    <div class="container padding-vert-30 margin-top-60">
        <div class="row">
            <!-- Contact Details -->
            <div class="col-md-4 margin-bottom-20">
                <h3 class="margin-bottom-10">@Resource.Контактная_информация</h3>
                <p>
                    <span class="fa-phone">@Resource.Номер_телефона:</span>@Model.PhoneNumber
                    <br>
                    <span class="fa-envelope">@Resource.Почта:</span>
                    <a href="mailto:@Model.Email">@Model.Email</a>
                </p>
                <p>
                    @Resource.Кыргызстан,
                    <br>@Resource.город_Каракол
                </p>
                
            </div>
            <!-- End Contact Details -->
            <!-- End Sample Menu -->
            <div class="col-md-1"></div>
            <!-- Disclaimer -->
            <div class="col-md-3 margin-bottom-20  text-center">
                <h3 class="color-gray margin-bottom-10">@Resource.У_вас_остались_вопросы</h3>
                <p>
                    @Resource.Оставьте_заявку
                    <br>@Resource.и_мы_с_вами_свяжемся
                </p>
                <input type="email" let="email" placeholder="Email">
                <br>
                <button class="btn btn-primary btn-lg margin-top-20" type="button" let="add-communications">@Resource.Отправить</button>
            </div>
            

            <!-- End Disclaimer -->
            <div class="clearfix"></div>
        </div>
        <div id="qoo-counter">
            <a href="#">
                <img src="http://qoo.by/counter/standard/001.png" alt="Счетчик посещаемости и статистика сайта">
                <div id="qoo-counter-visits" style="margin-top: -4px;"></div>
                <div id="qoo-counter-views" style="margin-top: -4px;"></div>
            </a>
        </div>
        <script type="text/javascript" src="http://qoo.by/counter.js"></script>
</div>
</div>
<!-- Footer Menu -->
<div id="footer">
    <div class="container">
        <div class="row">
            <div id="copyright" class="col-md-4">
                <p class="pull-right">(c) @DateTime.Now.Year Time Tour</p>
                

            </div>
        </div>
    </div>
</div>
<script src="@Url.Content("~/Scripts/Processors/communications.view.processor.js")"></script>
<script>
    $(() => {
        var config = {
            url: {
                add: '@Url.Action("AddInverse","Home")',
                add2: '@Url.Action("AddInverses","Home")'
            },
            resource: {
                addTitle: '@Resource.Создание_заявки',
                save: '@Resource.Сохранить',
                close: '@Resource.Закрыть',
                operationComplete: '@Resource.Операция_завершена',
                addIsComplete: '@Resource.Ваша_заявка_принята'
            }
        };
        var processor = new СommunicationsViewProcessor(config);
        processor.Start(); 
    })
</script>

Touring/Views/Shared/_sidebar.cshtml
@using KIT.Enums
@using Touring.ModelsVm


<ul class="social-icons pull-right hidden-xs" style="left: -44px !important; bottom: 420px;">
    <li class="social-en">
        <a href="@Url.Action("ChangeCulture", "Client", new { langEnum = Language.En })" title="English"></a>
    </li>
    <li class="social-ru">
        <a href="@Url.Action("ChangeCulture", "Client", new { langEnum = Language.Ru })" title="Русский"></a>
    </li>
</ul>
<ul class="social-icons pull-right hidden-xs">
    <li class="social-vk">
        <a href="@Model.Vk" target="_blank" title="Vk"></a>
    </li>
    <li class="social-instagram">
        <a href="@Model.Instagramm" target="_blank" title="Instagram"></a>
    </li>
    <li class="social-facebook">
        <a href="@Model.Fb" target="_blank" title="Facebook"></a>
    </li>
    <li class="social-youtube">
        <a href="@Model.Youtube" target="_blank" title="Youtube"></a>
    </li>
</ul>